# SemanticBKIOctoMap config

# Octree parameter
block_depth: 3 # Test-data octree depth (see Wang & Englot ICRA 2016)

# Kernel parameters
sf2: 10.0 # Actually sigma_0 in sparse kernel
ell: 1.0 # Length scale of the sparse kernel

# BGK Inference class prior pseudocounts
prior: 0.001 # each class

# Threshold on variance to distinguish known/unknown
var_thresh: 0.09

# Free/Occupied Thresholds
free_thresh: free_thresh
occupied_thresh: 0.7
